site_name: "Documentation | CAP"
site_author: cap.ooo
site_description: CAP is an open internet service that provides an activity and transaction history all assets (Token/NFTs/etc...) on the Internet Computer can integrate to.
site_url: https://docs.cap.ooo/
copyright: 'Â© 2021 Built by Fleek LLC'
repo_name: psychedelic/cap
repo_url: https://github.com/psychedelic/cap
theme:
  name: material
  custom_dir: overrides
  favicon: './imgs/favicon.ico'
  logo: './imgs/cap.png'
  font:
    text: 'Open Sans'
extra_css:
  - 'stylesheets/extra.css'
  - 'stylesheets/codehilite-theme.css'
markdown_extensions:
  - codehilite
  - admonition
  - attr_list
  - meta
  - toc:
      permalink: true
nav:
  - Welcome to CAP ðŸ‘‹: index.md
  - <b>Overview</b> ðŸ‘‘: "#"
  - What is CAP?: nft-list/getting-started.md
  - <b>Integrate to NFT/Token</b> âš¡: "#"
  - CAP SDK - Getting Started: canister-list/getting-started.md
  - Installing CAP in new Project: canister-list/getting-started.md
  - Migrating Old Project to CAP: canister-list/getting-started.md
  - <b>Show CAP Data in UI/Apps</b> ðŸ“œ: "#"
  - CAP JS - Getting Started: https://github.com/Psychedelic/DAB-js/
  - Surface Asset Histories: https://github.com/Psychedelic/DAB-js/
  - <b>Examples & Standards</b> ðŸ§°: "#"
  - NFT Example Integration: https://github.com/Psychedelic/DAB-js/
  - Token Example Integration: https://github.com/Psychedelic/DAB-js/
  - DIP-721 Token Standard: https://github.com/Psychedelic/DAB-js/
  - <b>Resources</b> ðŸ“š:
    - The Internet Computer: "https://dfinity.org/faq"
    - Disclaimer: resources/disclaimer.md
    - Trademark: resources/trademark.md
    - Privacy: resources/privacy.md
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/psychedelic/cap/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/cap_ois
    - icon: fontawesome/brands/discord
      link: https://discord.gg/yVEcEzmrgm